language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: "qk01AdOo/UNjTnonulS5NOSH3q+oCRdoWeE72MaZ1GFnEebA9cYHUeUoY/7jxRY7UG2wZPdl56IF6DiM5qavvh2nHVJVgNjtEaurzFrqBHaPIz57nq8SGf3PKcA4qJmwxkgrEtkptAhF0sLMlrpYJGQAkfMifTQETaVOl8W2KeIK4JjqeAXbkxR9IpyqvnKR0DYqhJZDhX+Z0/gvEZXzc4GZJrSgvsmO9L7lUSxRw9uWnzqkQq/Qd2MiAhAK1vEg0AdykfCKXcLQb1yPUMd6sVGgayTMLhf+rqJ9ZOk3DFHXXLQzLEnV8N0sP0P7efRa4JkP8WR8E908OeIAXCaq0qE3BZzF1mm1o1Lz/7UglZdNUuebzbID/1rQyY1TMOfF7Nk+NZCZXNbrQLpb2mNqAtPsVTEf48FNuyRY7uZ7IoiDhd7MpCZWCGBBi3FDNonOPB62PVeByAefAxnEvBJNBQHuZSNQr/Ek2WHV+swYkH29ngapJCb/0lavPCUsgaaaesKKA4zabBXkIgTRqLBGS4Ne3zIh1dYcaqcpXA0NSWlj4UNsC3pQIdzZpnIB6H/04VKQEMgl8AwBNkQKtgGLHf+3EDoQph1RpoLiUm6LioK1PrVy4wecws1MfnfFm+awOtzPPLsWy5Ys901j0j72WYpQkmOc9+7g9+5gklOlxR4="
  app: shrouded-inlet-26742
