language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: "Dwivygy8NmgnHDI8tVJlyJbHS2F+fv7R6j1l3HgqyRtDw0m2bZf43HGRMDRgW3Cf+iIzdsXLZef0i1Husp3kHIZlmpVNc48haFadU6Mp74KOgsg9/RNkOK3liS4qYTImceqUpzm/KmtbdGGZBijg8T0R7tWgOOLTYHfBA4+yrTfGcqJBY2fg9JiD5Cyw4sZly+V8AeHJ7Q8GukMigsasASZFKRSYoKbNScJelpsxB9ImNqzlHkMbrrMGOAObizUFUgw3WTiC+xemw16+mnSx05+r4u5hHTboVZ6MzL/75h2ZKBpaIOqeqQHkodssRcnvQeC0I3txm74sJUPOfxn1jyfWUJ+kNSVre4X5DaMpF4LTBn+32rqCfq4rqub12e7R03ls9L2w33XgBrNo3tgBSOzu30VdraGOx4xzAquD6mca+zhTbOfTrG9dtE+kBmDUrrpw5/VQ2Rsr4sIICWf4wfR2cn89A4YYt68HHB/pP9lbqfoAosnESMY3SgptknmNmw8FPE8s0y7B9Q3174lMvKkP4WoRCzKR892+/qVR+7sxIW0rySGWWPLg/kePvhTDGp8hDdxFEcwrLbwWsWKCHzgj8LslyHytgPLFL2jxV3WxffOmIhieZpuDVarUvf+qNZzCGdb592Lt0+BgAjt8ZPcuquW/Nme3nxaYxdROiaw="
    app: shrouded-inlet-26742
