language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: oDaRVPNKKgNG03/jCt5OojQ19FgzKEvgcZL/yOn2RxBES+lwAqvyEkINAFqWjVvPRnKGOVxCnF0WE0MhNbBJBbCw1+S9uu65IoI6P0LY4vtrIlB9faYO6hGt1wWAT2EHeIm5to+rumc33yx3epIp9+HRho8F11VTmLlVCMeGmVuSK5wOVim45uhB7V/y34h5HmQgeJy3fKLwbfmKBa/egdELPt2vLxpuVtRLfht1C/Zxr1dsekL8C+EwHlSVqXK6m1JFiVjO/8B6o9Lt66pxbzYJ2MGqeNG72Z99pDn6Y0pJsKTNTBan1JXZrrH6S1EP7KdqK94x9LirbGYuVR6LLBqheewaV+Hbi4tznxB1GnJ5gOjf7lxwHpTkpEHkEkwqIZZY60akq2X3wvyx+y4kwy8xz1nwJZ1u934eP3bti7QBIiJfV9rqwhfLDbNQNDeaV9kuJlq+FfgZX0hCJneuzhdQVvzpYkLCzobt6GNkh9e1Zei4rMN9+RBe0sxCuX7HAQ73/QGBCMyixUmDrrjbx0OJsTRQmfr7DzXNlS9nmpPvQLloU7CFKUESA05q5iMjpMgXHQZmWYL8prcErap2L9AWYU1f0a8I5GBthgemFm9UyMNxE1WW3jPqn8/AyJmNXRn/sm6SLBcr0Sk4wOQqtBXBk0LQhk6gjXe7lAoAiEw=
    app: shrouded-inlet-26742
