language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: bzU3vGHGkLYdtRu9nUYwjP/ZfTcqlAiQctx0lagskCCtfouD4DoV3SX0HJg4hxTy/5w5BR71XNbuxy0hMAqQtzYjPW4Kll6HtGga8ucTdmmSlNSBU2S9a6R4yPZVA3y8iJkgo8ZAVwyXpQEOFulbUhaun1ivTlBSdgVqkm4RKF81VSz29EwDRJof95LXKi1bBvJ3K6AI1HELBt3gdLI/yUS7xQ+l2VVi9DgTEvKftWg5vH4MI51HCUb0hHnoXXyw92bHcoB8Nadp0drKRSVlNDIxLDyfDzWB/NLBsrupUZokJJAqY79vcJcEHyx8qb70WXUvHupDQNLRVFn8hvAl9lyiBkmbf3IFhuvQAOaVsxosaf00OBLzv5ZYGPFKlIqwrNJOzlyxaw2kkVlatsGKhF9+pEwysXaNjcsTwZ0DXlU89ZS063Jjgzce7oIBd3sYqLgPf0gavuCd0jEmcUqvSST07oEsui5RX1a1RImknyL+JDkUtyEFosdRQsUJZSeIjKDOi7AnK0fttrEsHfqRAhCIQ50nWLnrfIJa/V2LEDAD+kNrJYZ9xi0cYImYYDYcrHowoKg4J8cz5lVlX8hc2HsVsa65vhom9NWkYN5k/CnpdOrx97u43clCcMXVK80OIvDtdGIQNHQl9FrjCzNHLW5ddcMbee3kxa+9K17puCU=
  app: shrouded-inlet-26742
